name: Sync from yaho-ma/nuviora to Nuviora/beck-end

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout beck-end
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Add yaho-ma/nuviora as remote
        run: |
          git remote add upstream https://github.com/yaho-ma/nuviora.git
          git fetch upstream

      - name: Configure Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Merge changes
        run: |
          git checkout main
          git merge --allow-unrelated-histories upstream/main || true
          git diff --name-only --diff-filter=U | xargs git checkout --ours || true
          git add .

          # Check updates in the main branch
          if ! git diff --cached --quiet; then
            git commit -m "Auto-sync from yaho-ma/nuviora (kept beck-end files)"
          else
            echo "No changes to commit"
          fi

      - name: Push changes
        run: |
          # Check for new commits in the main branch
          if [ "$(git rev-parse HEAD)" != "$(git ls-remote origin main | awk '{print $1}')" ]; then
            git push --force https://x-access-token:${{ secrets.GH_PAT }}@github.com/Nuviora/beck-end.git main
          else
            echo "No new commits to push"
          fi
